# Generated by Django 5.1.1 on 2024-10-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Seller", "Seller"), ("Buyer", "Buyer")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
