# Generated by Django 5.1.1 on 2024-10-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_cart_created_at_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="banner",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
